package com.njust.wanyuan_display.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.njust.wanyuan_display.greenDao.Adv;
import com.njust.wanyuan_display.greenDao.AisleInfo;
import com.njust.wanyuan_display.greenDao.AisleMerge;
import com.njust.wanyuan_display.greenDao.GoodsInfo;
import com.njust.wanyuan_display.greenDao.MachineInfo;
import com.njust.wanyuan_display.greenDao.MachineState;
import com.njust.wanyuan_display.greenDao.OrderRecord;
import com.njust.wanyuan_display.greenDao.SettingInfo;
import com.njust.wanyuan_display.greenDao.Transaction;

import com.njust.wanyuan_display.greenDao.AdvDao;
import com.njust.wanyuan_display.greenDao.AisleInfoDao;
import com.njust.wanyuan_display.greenDao.AisleMergeDao;
import com.njust.wanyuan_display.greenDao.GoodsInfoDao;
import com.njust.wanyuan_display.greenDao.MachineInfoDao;
import com.njust.wanyuan_display.greenDao.MachineStateDao;
import com.njust.wanyuan_display.greenDao.OrderRecordDao;
import com.njust.wanyuan_display.greenDao.SettingInfoDao;
import com.njust.wanyuan_display.greenDao.TransactionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig advDaoConfig;
    private final DaoConfig aisleInfoDaoConfig;
    private final DaoConfig aisleMergeDaoConfig;
    private final DaoConfig goodsInfoDaoConfig;
    private final DaoConfig machineInfoDaoConfig;
    private final DaoConfig machineStateDaoConfig;
    private final DaoConfig orderRecordDaoConfig;
    private final DaoConfig settingInfoDaoConfig;
    private final DaoConfig transactionDaoConfig;

    private final AdvDao advDao;
    private final AisleInfoDao aisleInfoDao;
    private final AisleMergeDao aisleMergeDao;
    private final GoodsInfoDao goodsInfoDao;
    private final MachineInfoDao machineInfoDao;
    private final MachineStateDao machineStateDao;
    private final OrderRecordDao orderRecordDao;
    private final SettingInfoDao settingInfoDao;
    private final TransactionDao transactionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        advDaoConfig = daoConfigMap.get(AdvDao.class).clone();
        advDaoConfig.initIdentityScope(type);

        aisleInfoDaoConfig = daoConfigMap.get(AisleInfoDao.class).clone();
        aisleInfoDaoConfig.initIdentityScope(type);

        aisleMergeDaoConfig = daoConfigMap.get(AisleMergeDao.class).clone();
        aisleMergeDaoConfig.initIdentityScope(type);

        goodsInfoDaoConfig = daoConfigMap.get(GoodsInfoDao.class).clone();
        goodsInfoDaoConfig.initIdentityScope(type);

        machineInfoDaoConfig = daoConfigMap.get(MachineInfoDao.class).clone();
        machineInfoDaoConfig.initIdentityScope(type);

        machineStateDaoConfig = daoConfigMap.get(MachineStateDao.class).clone();
        machineStateDaoConfig.initIdentityScope(type);

        orderRecordDaoConfig = daoConfigMap.get(OrderRecordDao.class).clone();
        orderRecordDaoConfig.initIdentityScope(type);

        settingInfoDaoConfig = daoConfigMap.get(SettingInfoDao.class).clone();
        settingInfoDaoConfig.initIdentityScope(type);

        transactionDaoConfig = daoConfigMap.get(TransactionDao.class).clone();
        transactionDaoConfig.initIdentityScope(type);

        advDao = new AdvDao(advDaoConfig, this);
        aisleInfoDao = new AisleInfoDao(aisleInfoDaoConfig, this);
        aisleMergeDao = new AisleMergeDao(aisleMergeDaoConfig, this);
        goodsInfoDao = new GoodsInfoDao(goodsInfoDaoConfig, this);
        machineInfoDao = new MachineInfoDao(machineInfoDaoConfig, this);
        machineStateDao = new MachineStateDao(machineStateDaoConfig, this);
        orderRecordDao = new OrderRecordDao(orderRecordDaoConfig, this);
        settingInfoDao = new SettingInfoDao(settingInfoDaoConfig, this);
        transactionDao = new TransactionDao(transactionDaoConfig, this);

        registerDao(Adv.class, advDao);
        registerDao(AisleInfo.class, aisleInfoDao);
        registerDao(AisleMerge.class, aisleMergeDao);
        registerDao(GoodsInfo.class, goodsInfoDao);
        registerDao(MachineInfo.class, machineInfoDao);
        registerDao(MachineState.class, machineStateDao);
        registerDao(OrderRecord.class, orderRecordDao);
        registerDao(SettingInfo.class, settingInfoDao);
        registerDao(Transaction.class, transactionDao);
    }
    
    public void clear() {
        advDaoConfig.clearIdentityScope();
        aisleInfoDaoConfig.clearIdentityScope();
        aisleMergeDaoConfig.clearIdentityScope();
        goodsInfoDaoConfig.clearIdentityScope();
        machineInfoDaoConfig.clearIdentityScope();
        machineStateDaoConfig.clearIdentityScope();
        orderRecordDaoConfig.clearIdentityScope();
        settingInfoDaoConfig.clearIdentityScope();
        transactionDaoConfig.clearIdentityScope();
    }

    public AdvDao getAdvDao() {
        return advDao;
    }

    public AisleInfoDao getAisleInfoDao() {
        return aisleInfoDao;
    }

    public AisleMergeDao getAisleMergeDao() {
        return aisleMergeDao;
    }

    public GoodsInfoDao getGoodsInfoDao() {
        return goodsInfoDao;
    }

    public MachineInfoDao getMachineInfoDao() {
        return machineInfoDao;
    }

    public MachineStateDao getMachineStateDao() {
        return machineStateDao;
    }

    public OrderRecordDao getOrderRecordDao() {
        return orderRecordDao;
    }

    public SettingInfoDao getSettingInfoDao() {
        return settingInfoDao;
    }

    public TransactionDao getTransactionDao() {
        return transactionDao;
    }

}
